### ISSUE TITLE
Kookma Plugin Library

### ISSUE THREAD

**Issue by diego898** [kookma/TW-Refnotes#11]
Hello Mohammad! 

I'm just wondering if its on purpose that refnotes is not in the Kookma Plugin Library?

**Comment by kookma** [comment]
Hi @diego898 
The current Release is not a Node.JS version that is why it is not included in Kookma Plugin Library. I will work on Refnote hopefully after TW 5.1.23 and I plan to add some new features and fix some reported issue. I then will add it to Kookma Plugin Library! I appreciate to submit any issues or feature request in Refnotes discussion board or issues section.

**Comment by kookma** [comment]
Hi Diego,
 Now Refnotes distributed using Kookma Plugin Library!
