### ISSUE TITLE
Using <<ref tid>> in fnote

### ISSUE THREAD

**Issue by abruski** [kookma/TW-Refnotes#15]
Hello,
I am new to tiddlywiki.
Is there anyway to include reference in a fnote. I want the reference to appear as a superscript number?
Maybe something like` <<fnote <<ref Oviawe1983>> >>`

or maybe make the ref tag closable. For example: `<ref Oviawe1983> Some text </ref>`

**Comment by kookma** [comment]
Hi abruski,
 Actually you have requested to use another style type. The ref uses APA ed7 style: https://apastyle.apa.org/style-grammar-guidelines/references/examples.

So, you need to have a different style which requires to add the style yourself. Read the documentation, but if you are new it is hard to implement! You can go to Tiddlywiki Google forum and see if there is available one there!
