### ISSUE TITLE
[Feature request] Backlinks in bibtex references

### ISSUE THREAD

**Issue by SonephetR2** [kookma/TW-Refnotes#16]
Thanks for this great plugin. I'm noticing that references don't display backlinks at the moment. This would probably be a great addition to the "More details" tab in $:/plugins/kookma/refnotes/viewtemplates/helper.

**Comment by kookma** [comment]
Thank you @SonephetR2. I think this makes sense!
Th implementation is not straight forward as <<ref mybook>> does not create a link! But it is possible!
I think we need to clone part of showrefs for this purpose!

I add this as an enhancement and will try to implement for next release! If you have a better solution or you can make a PR I highly welcome!

**Comment by SonephetR2** [comment]
Thanks a lot @kookma :)

Wouldn't using a filter expression offer a reasonable way forward, though perhaps not the least query intensive? My skillset is still very limited and I think I can't pull this off yet as I haven't been able to get past an issue with Current Tiddler but slapping ```
<$list filter="[search:[RefName]
{{{ [!is[system]search:[<currentTiddler>] -[<currentTiddler>] }}}" />
``` at the end of $:/plugins/kookma/refnotes/viewtemplates/helper seemed like a straightforward approach.

**Comment by kookma** [comment]
@SonephetR2 well yes, if you put something like below

```
<ol>
<$list filter="[!is[system]search:text<currentTiddler>]">
<li><$link/></li>
</$list>
</ol>
```

at the end of `$:/plugins/kookma/refnotes/viewtemplates/helper` it will work but also any other type of occurrences of current tiddler will be listed!

So, go with what you proposed for now and I will see if there is any better solution or use this one and accepting other occurrences of ref tiddler.

**Comment by SonephetR2** [comment]
Thanks a lot @kookma , much better :)
Indeed, as is, this may not be technically perfect in all use cases, but it definitely is for mine!

**Comment by kookma** [comment]
Added to Refnotes 1.8.0
