### ISSUE TITLE
Update documentation: Reference to bibtext importer 

### ISSUE THREAD

**Issue by pat-githubber** [kookma/TW-Refnotes#17]
Hello Mohamma,

First of all, thank you so much for this great plugin! Extremely helpful and I would not be able to create it.
Second, in the [documentation](https://kookma.github.io/TW-Refnotes/) under **What is Refnotes plugin?**, it says:

> Refnotes can create bibliography, but for the best performance, the use of the official **bibtex importer** plugin is recommended.

However, Refnote does not recognize an inserted bibtex entry using the field **Paste your Bibtex Entry here** without the bibtex importer plugin. Therefore, I think the stated line above should be placed under the section **Install** otherwise it is confusing.

Thank you!:)
All the best,
Patrick

**Comment by kookma** [comment]
@pat-githubber 
Thank you Patrick, I will correct the documentation!

**Comment by kookma** [comment]
Note: Paste your Bibtex Entry here  works with TW 5.2.0 and it uses a deserializer from official BibTeX importer.
So both are required! I added this to documentation!
