### ISSUE TITLE
Refnotes does not work with TiddlyWiki version 5.1.23

### ISSUE THREAD

**Issue by pat-githubber** [kookma/TW-Refnotes#18]
Hello Mohamma, 

in TiddlyWiki version [5.1.23](https://tiddlywiki.com/) (latest version on tiddlywiki.com), I installed Refnotes according to the [documentation](https://kookma.github.io/TW-Refnotes/) including the bibtex importer and after inserting a bibtex entry using the field **Paste your Bibtex Entry here**, TiddlyWiki wants to import the bibtex entry but Refnotes does not recognize it as a bibtex (see image below).

In the [pre-release version 5.2.0](https://tiddlywiki.com/prerelease/), it works. However, it only works, when I download the version 5.2.0 and install Refnotes there. When I [upgrade](https://tiddlywiki.com/static/Upgrading.html) my version 5.1.23 to 5.2.0, it however does not work.

I have an assumption: The system tiddler '$:/core' is not being upgraded. After upgrading and replacing the system tiddler '$:/core' with the same tiddler from the downloaded version 5.2.0, it works somehow (but I have no clue about this).

Thank you and all the best,
Patrick

![image](https://user-images.githubusercontent.com/87087327/133739415-f199256d-899a-4e13-b687-f22f56cacf34.png)

**Comment by kookma** [comment]
@pat-githubber 
Patrick, I am not sure how you have updated your wiki. Please take a backup first and do as per below instructions on a copy of your wiki (to prevent any data loss)

- download an empty.html 5.2.0 from https//tiddlywiki.com/prerelease
- open the empty.html and  drag and drop your current wiki into it
- install the oficial bibtex importer
- install the Refnotes latest

This should work! If NOT, open $:/ControlPanel, Plugins Tab and then open Refnotes. Check if any tiddler of Refnotes has been overwritten!

**Comment by pat-githubber** [comment]
@kookma 
Yes, this is how I did it.

Your last sentence explains the issue I had and fills my knowledge gap. Thank you!
