### ISSUE TITLE
Add explaination why tiddler field is beautifully displayed

### ISSUE THREAD

**Issue by linonetwo** [kookma/TW-Refnotes#20]
I am confused why https://kookma.github.io/TW-Refnotes/#leal-2018 display its all fields when rendered, this seem not to be a tw feature, is some of your other plugin, or a feature in tw-refnotes enabled this?

Maybe I miss something in your tutorial?

**Comment by kookma** [comment]
Hi @linonetwo - would you send a screenshot?
In my test it works like other entries!

**Comment by linonetwo** [comment]
![截屏2021-09-18 下午6 35 20](https://user-images.githubusercontent.com/3746270/133885907-bcdbbba6-654c-4687-9f53-7dfb07078f3a.png)

This, its text is empty , but it is displaying its field content. Is there a view template in your plugin?

**Comment by kookma** [comment]
What you sent is a correct display of a bibtex entry!
A bibtex is stored in tiddler fields! A custom view template is used here to show the contents of field!

Every tiddler tagged with `bibtex-entry` uses the same viewtemplate!

**Comment by linonetwo** [comment]
Actually, what confused me is it works even I remove all the tags...

![截屏2021-09-18 23 39 05](https://user-images.githubusercontent.com/3746270/133894338-ae00d81f-a675-444c-8105-a5ab568b9051.png)

Can you point out the source file of this viewtemplete? I couldn't search it out, thanks!

**Comment by kookma** [comment]
@linonetwo - See $:/plugins/kookma/refnotes/viewtemplates/main
and all tiddlers under `$:/plugins/kookma/refnotes/viewtemplates` namespace!

**Comment by linonetwo** [comment]
Thank you for this detailed explaination!
