### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by hgj44d** [kookma/TW-Refnotes#21]
Hello Mohammad,

As started in a discussion on [Talk TiddlyWiki](https://talk.tiddlywiki.org/t/how-do-you-handle-bibtex-sources/1134) I suggest to improve the documentation on some places:

# Install Guide on Node.js 

1. **Change the heading**. I wouldn't call the heading of the Node.js Installation _Client-server configuration_. Most people don't know what that means and it would be easier if you just call it _Installation on Node.js_ or something which is more obvious for new users. 

2. **Separate the installation methods in two parts**. The way you structured the installation part seems that there is only one method for installing it on Node.js, namely the global installation. I think that a newbie will start the global configuration and after finishing it you will see the green box at the end with the hint that you can just install it local. My personal opinion is that the local installation suits the most people and is way more easier (you just have to copy a folder). So I suggest to split the Installation part in local and global installation (with local first). Btw, even on the official TiddlyWiki documentation it's to complicated to understand how you install plugins on node.js and that you can easily install it locally and just copy a folder.

I modified your _Install_ tiddler and did a screenshot, so it's easier for you to understand how I would change it:

<img width="497" alt="Screenshot-Installation-new" src="https://user-images.githubusercontent.com/72733918/137284548-c4b9b117-db7c-4b33-8f66-f8e59756908b.png">

# BibTeX

Most people outside of academy don't even know what BibTeX is. I would suggest to shortly describe what BibTeX in general is and what the benefits are. This will help other people to understand the purpose of the plugin (if they never heard of BibteX).
Here is my suggested text, which I would put in the first in tiddler _Refnotes Plugin_ under the section _What is Refnotes plugin?_:

> BibTeX is a widely adopted file format to store bibliographical information (books, websites, acrticles etc.) in an easy human-readable structure. An example of a BibTeX entry:
> 
> ```
> @article{nash51,
>   author  = "Nash, John",
>   title   = "Non-cooperative Games",
>   journal = "Annals of Mathematics",
>   year    = 1951,
>   volume  = "54",
>   number  = "2",
>   pages   = "286--295"
> }
> ```
> You can create a BibTeX file with various [[tools|Tools for Generating BibTeX Entry]] and import it with the official [[BibTeX Importer Plugin]] into your TiddlyWiki, which creates a tiddler for every BibteX entry and stores the various information in fields. After that you can use Refnotes to cite your bibliography with `<<ref nash51>>`.

If I read your Tutorial correctly, there is no word about that you first have to import the .bib file and that you have to press the button _Process New Entries_ (you only mention it in the _Quick tutorial_ tab, but I think most people will skip the _Quick tutorial_ tab because there is to less information to understand it). I think most people will start the tutorial and wonder how to get the _tid_ in `<<ref tid>>`. You mention on the Install part that you need the official bibtex importer, but I think the workflow of how to import and process the BibTeX entries is missing.

I would start the _Tutorial_ tiddler with the tab _Bibliography_ (because I just guess that most people are interested in the ref macro). I would rename the _Quick tutorial_ to _Cheat Sheet_ and put it as the last tab because I think most people will skip the _Quick tutorial_ tab because there is to less information to understand it. Inside the _Bibliography_ tab I would start with a new tab  called _Introduction_ where you describe what steps you need **before** you can even call `<<ref tid>>`:

> 1. Create your BibTeX file (e.g. library.bib) with [[Tools for Generating BibTeX Entry]]
> 2. Import your BibTeX file with the official [[BibTeX Importer Plugin]]
> 3. Press _Process New Entries_ in the sidebar
>
> Now you have every BibTeX entry stored in a separate tiddler and the tiddler is tagged with _bibtex-entry_. The default name of the tiddler is the citation key which is stored in your .bib-file. 

In the tiddler [[Tools for Generating BibteX Entry]] I would add some additional text:

> There are various ways how you can generate a BibTeX file to be imported in Refnotes. 
> 
> ! Install a Reference Manager
> 
> One way to generate a BibTeX file is to install a reference manager where you can create your own Bibliographic database in the BibTeX file format. Some reference managers (like JabRef) use by default the BibTeX file format and others have a way to export the database in the BibTeX file format. There are also browser extension available, which is very handy when you surf the web and want an easy way to bookmark a website (see the section Website below) or PDF. 
> 
> !! JabRef
> 
> JabRef stores the database by default in the BibTeX format. There is also a browser extension available.
> 
> !! Zotero
> 
> Zotero doesn't use the BibTeX file format by default, but you can export the database in the BibTeX format. There is also a very good extension available which gives you more control over the export, which is called [[Better BibTeX|https://retorque.re/zotero-better-bibtex/]]. A browser extension is also available.
> 
> ! Online BibTeX generator
> 
> There are several websites where you can generate BibTeX entries and drag-and-drop it into Refnotes. 
> 
> ! Some extra information about Websites
> 
> There are 14 standard BibTeX entry types (see [[here|https://www.bibtex.com/e/entry-types/]]) defined. TiddlyWiki stores the entry type in the field bibtex-entry-type. It doesn't exist an official Website BibTeX entry type, altough Refnotes has a way to handle bibtex-entry-type Website. To overcome this you can specify in most reference managers your own BibTeX entry type called Website. You need at least the following entries: URL, Title	and Year.

I hope this helps to understand the beauty of Refnotes better. 

@kookma feel free to discuss. Copy the text inside the Refnotes website or change it as you want.

**Comment by kookma** [comment]
Thank you @hgj44d.
This is addressed in 1.7.4 and 1.8.0
