### ISSUE TITLE
KaTeX plugin breaks numbering

### ISSUE THREAD

**Issue by AzureDVBB** [kookma/TW-Refnotes#23]
When using the KaTeX official plugin empty lines (to separate text into blocks) will restart the numbering of the refnotes in the text, but appear correctly in \<\<showfnotes>>.

Minimum Tiddlywiki Setup to reproduce:

Core 5.2.2
KaTeX 5.2.2
Refnotes 1.7.3

Test Tiddler:

```
a<<fnote "One">>

b<<fnote "Two">>
c<<fnote "Three">>d<<fnote "Four">>

---

<<showfnotes>>
```

Result:

a<sup>1</sup>
b<sup>1</sup> c<sup>2</sup>d<sup>3</sup>

---

1. One
1. Two
1. Three
1. Four

**Comment by kookma** [comment]
I will investigate!
KaTeX uses restart numbering per tiddler! It uses CSS numbering for equations. 
I did not note this may interfere with Refnotes.

**Comment by kookma** [comment]
Hi @AzureDVBB 
See solution here: https://github.com/Jermolene/TiddlyWiki5/discussions/6607

Actually after installing the KaTeX plugin, add a new stylesheet tiddler (the one tagged with `$:/tags/Stylesheet`) with below content: 

```
.tc-tiddler-frame { counter-reset: fnote-count katexEqnNo;}
```

**Comment by AzureDVBB** [comment]
Thank you for looking into it. That indeed solves the issue!

Although with my homebrew theme plugin adding it as a separate stylesheet tiddler didn't work.
I had to add that line to the plugin's `stylesheet.tid` file right at the end to make it work.

Tested all the core theme plugins as well as one or two random theme plugins I found with a quick search, but none seem to have the same issue and they just worked with the separate stylesheet tiddler.

I saw you were investigating it and [reordering tiddlers worked](https://github.com/Jermolene/TiddlyWiki5/discussions/6607#discussioncomment-2526100) as well.
I don't know how to do that and I'm not as well versed to investigate further unfortunately.
It's a bit strange however since the theme plugin style does not actually touch `.tc-tiddler-frame` in there.

I have made a minimal tiddlywiki if that would be useful to you [in this ghist](https://gist.github.com/AzureDVBB/3a7bb218b72cba7093583e9b050e3b5f).

**Comment by kookma** [comment]
Hi @AzureDVBB 
I investigated your theme and found an error in `$:/themes/azuredvbb/better-centralized-story/styles.tid`
When it fixed the numbering are displayed correctly.

Correct the last lines of `$:/themes/azuredvbb/better-centralized-story/styles.tid` as below

```
		min-width: {{$:/themes/tiddlywiki/vanilla/metrics/sidebarwidth}};
	padding-left: 0;
	}
}
""">>
```

There was an extra `}` which was removed

**Comment by AzureDVBB** [comment]
Thank you so much! 
It's a little embarrassing how a single curly brace can ruin your day.

The stylesheet tiddler is the option I went for as it seems like a more robust solution that I can undo if it is fixed in the future.

Should I close the issue now that a suitable workaround is found or should I keep it open until a more permament solution is made?

**Comment by kookma** [comment]
> Should I close the issue now that a suitable workaround is found or should I keep it open until a more permanent solution is made?

I close the issue and I will add short note into Refnotes documentation.
